ENV=$1
VER=$ENV.`date "+%Y%m%d%H%M"`
DOCKER_TAG="appiriodevops/tc-connect2sf:$VER"
DOCKER_TAG_SED="appiriodevops\/tc-connect2sf:$VER"

source ./$ENV.env

./docker-build.sh $DOCKER_TAG

docker push $DOCKER_TAG

cat tc-connect2sf.yml.template | sed s/@@DOCKER_TAG@@/$DOCKER_TAG_SED/g | sed s/@@LOG_FILE@@/$LOG_FILE/g | sed s/@@LOG_LEVEL@@/$LOG_LEVEL/g | sed s/@@RABBITMQ_URL@@/$RABBITMQ_URL/g | sed s/@@OWNER_ID@@/$OWNER_ID/g | sed s/@@AWS_REGION@@/$AWS_REGION/g | sed s/@@AWS_ENDPOINT@@/$AWS_ENDPOINT/g | sed s/@@AWS_ACCESS_KEY_ID@@/$AWS_ACCESS_KEY_ID/g | sed s/@@AWS_SECRET_ACCESS_KEY@@/$AWS_SECRET_ACCESS_KEY/g | sed s/@@IDENTITY_SERVICE_URL@@/$IDENTITY_SERVICE_URL/g | sed s/@@IDENTITY_SERVICE_CLIENT_ID@@/$IDENTITY_SERVICE_CLIENT_ID/g | sed s/@@IDENTITY_SERVICE_CLIENT_SECRET@@/$IDENTITY_SERVICE_CLIENT_SECRET/g | sed s/@@SALESFORCE_CLIENT_ID@@/$SALESFORCE_CLIENT_ID/g | sed s/@@SALESFORCE_CLIENT_SUBJECT@@/$SALESFORCE_CLIENT_SUBJECT/g | sed s/@@SALESFORCE_CLIENT_AUDIENCE@@/$SALESFORCE_CLIENT_AUDIENCE/g | sed s/@@QUEUE_PROJECT_CREATED@@/$QUEUE_PROJECT_CREATED/g | sed s/@@QUEUE_PROJECT_LAUNCHED@@/$QUEUE_PROJECT_LAUNCHED/g | sed s/@@KEY_FILE_NAME@@/$KEY_FILE_NAME/g > tc-connect2sf.yml 

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY

./ecs-deploy.sh tc-$1
